import { ThemeId } from '../types/settings'

export type ThemeTokenMap = Record<string, string>

const BADGE_TOKENS: ThemeTokenMap = {
  'size-small-bg': '#e8f5e9',
  'size-small-text': '#3d7a52',
  'size-medium-bg': '#fff8e1',
  'size-medium-text': '#9a7b4f',
  'size-large-bg': '#fde8e8',
  'size-large-text': '#c45c5c',
  'color-filter-label': '#111111',
}

export const THEME_TOKENS: Record<ThemeId, ThemeTokenMap> = {
  padrao: {
    ...BADGE_TOKENS,
    'color-bg-page': '#f7f5f0',
    'color-bg-surface': '#fffdf9',
    'color-bg-elevated': '#faf7f2',
    'color-bg-sidebar': '#0c1222',
    'color-bg-sidebar-hover': 'rgba(255, 255, 255, 0.06)',
    'color-bg-sidebar-active': 'rgba(201, 169, 98, 0.2)',
    'color-bg-table-header': '#0c1222',
    'color-bg-input': '#faf7f2',
    'color-border': '#e8e2d6',
    'color-border-strong': '#d4bc82',
    'color-text': '#2a2620',
    'color-text-muted': '#8a8175',
    'color-text-soft': '#5c564c',
    'color-text-inverse': '#fffdf9',
    'color-accent': '#c9a962',
    'color-accent-dark': '#a68b4b',
    'color-accent-glow': 'rgba(201, 169, 98, 0.25)',
    'color-accent-secondary': '#5b9bd5',
    'color-heading': '#0c1222',
    'color-sidebar-text': 'rgba(255, 255, 255, 0.65)',
    'color-sidebar-text-active': '#c9a962',
    'color-btn-primary-bg': '#c9a962',
    'color-btn-primary-text': '#0c1222',
    'color-btn-primary-hover': '#a68b4b',
    'color-toast-bg': '#fffdf9',
    'color-toast-text': '#2a2620',
    'color-toast-border': '#e8e2d6',
    'color-toast-close': '#4a4a4a',
    'color-error-bg': '#fef8f8',
    'color-error-border': '#f5d0d0',
    'color-error-text': '#9b4545',
    'shadow-card': '0 2px 16px rgba(12, 18, 34, 0.05)',
    'shadow-card-hover': '0 4px 16px rgba(30, 95, 194, 0.12)',
  },
  escuro: {
    ...BADGE_TOKENS,
    'color-bg-page': '#1a1d23',
    'color-bg-surface': '#23272f',
    'color-bg-elevated': '#2c313a',
    'color-bg-sidebar': '#141820',
    'color-bg-sidebar-hover': 'rgba(91, 141, 213, 0.12)',
    'color-bg-sidebar-active': 'rgba(59, 99, 168, 0.35)',
    'color-bg-table-header': '#1e3a5f',
    'color-bg-input': '#2c313a',
    'color-border': '#3d4450',
    'color-border-strong': '#3b6398',
    'color-text': '#e8eaed',
    'color-text-muted': '#9aa3b2',
    'color-text-soft': '#b8c0cc',
    'color-text-inverse': '#f0f2f5',
    'color-accent': '#5b8fd6',
    'color-accent-dark': '#3b6398',
    'color-accent-glow': 'rgba(91, 143, 214, 0.3)',
    'color-accent-secondary': '#7eb3e8',
    'color-heading': '#f0f2f5',
    'color-sidebar-text': 'rgba(232, 234, 237, 0.7)',
    'color-sidebar-text-active': '#7eb3e8',
    'color-btn-primary-bg': '#3b6398',
    'color-btn-primary-text': '#f0f2f5',
    'color-btn-primary-hover': '#2d4d78',
    'color-toast-bg': '#2c313a',
    'color-toast-text': '#e8eaed',
    'color-toast-border': '#3d4450',
    'color-toast-close': '#9aa3b2',
    'color-error-bg': '#3a2528',
    'color-error-border': '#6b3a40',
    'color-error-text': '#f0a8a8',
    'shadow-card': '0 2px 16px rgba(0, 0, 0, 0.25)',
    'shadow-card-hover': '0 4px 20px rgba(59, 99, 168, 0.2)',
  },
  claro: {
    ...BADGE_TOKENS,
    'color-bg-page': '#f0f6fc',
    'color-bg-surface': '#ffffff',
    'color-bg-elevated': '#f8fbff',
    'color-bg-sidebar': '#1e4a7a',
    'color-bg-sidebar-hover': 'rgba(255, 255, 255, 0.1)',
    'color-bg-sidebar-active': 'rgba(135, 185, 235, 0.35)',
    'color-bg-table-header': '#2a6cb8',
    'color-bg-input': '#f8fbff',
    'color-border': '#d0e3f5',
    'color-border-strong': '#87b9eb',
    'color-text': '#1a2e42',
    'color-text-muted': '#5a7a94',
    'color-text-soft': '#3d5a73',
    'color-text-inverse': '#ffffff',
    'color-accent': '#2a6cb8',
    'color-accent-dark': '#1e4a7a',
    'color-accent-glow': 'rgba(42, 108, 184, 0.2)',
    'color-accent-secondary': '#87b9eb',
    'color-heading': '#1a2e42',
    'color-sidebar-text': 'rgba(255, 255, 255, 0.85)',
    'color-sidebar-text-active': '#ffffff',
    'color-btn-primary-bg': '#2a6cb8',
    'color-btn-primary-text': '#ffffff',
    'color-btn-primary-hover': '#1e4a7a',
    'color-toast-bg': '#ffffff',
    'color-toast-text': '#1a2e42',
    'color-toast-border': '#d0e3f5',
    'color-toast-close': '#4a5568',
    'color-error-bg': '#fff5f5',
    'color-error-border': '#f5c4c4',
    'color-error-text': '#b42318',
    'shadow-card': '0 2px 12px rgba(42, 108, 184, 0.08)',
    'shadow-card-hover': '0 4px 16px rgba(42, 108, 184, 0.15)',
  },
}

export function applyThemeTokens(themeId: ThemeId) {
  const root = document.documentElement
  root.setAttribute('data-theme', themeId)
  const tokens = THEME_TOKENS[themeId]
  for (const [key, value] of Object.entries(tokens)) {
    root.style.setProperty(`--${key}`, value)
  }
}

export function migrateThemeId(stored: string): ThemeId {
  const map: Record<string, ThemeId> = {
    luxury: 'padrao',
    midnight: 'escuro',
    pearl: 'claro',
    padrao: 'padrao',
    escuro: 'escuro',
    claro: 'claro',
  }
  return map[stored] ?? 'padrao'
}
